cmake_minimum_required(VERSION 3.22)

if(NOT DEFINED LIBRARY_NAME)
    set(LIBRARY_NAME blendFile)
endif()
if(NOT DEFINED BOUNDARY_LABEL)
    set(BOUNDARY_LABEL reader)
endif()
string(TOLOWER "${LIBRARY_NAME}" required_library)

if(NOT DEFINED TARGET_FILE)
    set(reply_dir "${BUILD_DIR}/.cmake/api/v1/reply")
    file(GLOB indexes "${reply_dir}/index-*.json")
    if(NOT indexes)
        message(FATAL_ERROR "No generated CMake File API reply; reconfigure the build")
    endif()
    list(SORT indexes ORDER DESCENDING)
    list(GET indexes 0 index_file)
    file(READ "${index_file}" index)
    string(JSON codemodel_file GET "${index}"
        reply client-${LIBRARY_NAME} codemodel-v2 jsonFile)
    file(READ "${reply_dir}/${codemodel_file}" codemodel)
    string(JSON configuration_count LENGTH "${codemodel}" configurations)
    math(EXPR configuration_last "${configuration_count} - 1")
    foreach(configuration_index RANGE ${configuration_last})
        string(JSON name GET "${codemodel}" configurations ${configuration_index} name)
        if(NOT name STREQUAL CONFIG)
            continue()
        endif()
        string(JSON target_count LENGTH "${codemodel}"
            configurations ${configuration_index} targets)
        math(EXPR target_last "${target_count} - 1")
        foreach(target_index RANGE ${target_last})
            string(JSON name GET "${codemodel}"
                configurations ${configuration_index} targets ${target_index} name)
            if(name STREQUAL "${LIBRARY_NAME}Tests")
                string(JSON target_file GET "${codemodel}"
                    configurations ${configuration_index} targets ${target_index} jsonFile)
                set(TARGET_FILE "${reply_dir}/${target_file}")
            endif()
        endforeach()
    endforeach()
    if(NOT DEFINED TARGET_FILE)
        message(FATAL_ERROR "No generated ${LIBRARY_NAME}Tests link information for '${CONFIG}'")
    endif()
endif()

file(READ "${TARGET_FILE}" target)
string(JSON fragment_count LENGTH "${target}" link commandFragments)
if(fragment_count EQUAL 0)
    message(FATAL_ERROR "Generated ${BOUNDARY_LABEL} link information does not contain ${LIBRARY_NAME}")
endif()
math(EXPR fragment_last "${fragment_count} - 1")
set(reader_found FALSE)
set(system_libraries kernel32 user32 gdi32 winspool shell32 ole32 oleaut32 uuid
    comdlg32 advapi32 m dl pthread rt)
foreach(fragment_index RANGE ${fragment_last})
    string(JSON role GET "${target}" link commandFragments ${fragment_index} role)
    if(NOT role STREQUAL "libraries")
        continue()
    endif()
    string(JSON fragment GET "${target}" link commandFragments ${fragment_index} fragment)
    separate_arguments(libraries NATIVE_COMMAND "${fragment}")
    foreach(library IN LISTS libraries)
        get_filename_component(name "${library}" NAME)
        string(TOLOWER "${name}" name)
        string(REGEX REPLACE "^(-l|lib)" "" name "${name}")
        string(REGEX REPLACE "\\.(lib|a|so(\\.[0-9.]+)?|dylib)$" "" name "${name}")
        if(name STREQUAL required_library)
            set(reader_found TRUE)
            continue()
        endif()
        if(NOT name IN_LIST system_libraries)
            message(FATAL_ERROR "Forbidden generated ${BOUNDARY_LABEL} link dependency: ${library}")
        endif()
    endforeach()
endforeach()
if(NOT reader_found)
    message(FATAL_ERROR "Generated ${BOUNDARY_LABEL} link information does not contain ${LIBRARY_NAME}")
endif()