if(NOT TOOL OR NOT WRITER OR NOT FIXTURES OR NOT WORK_DIR)
    message(FATAL_ERROR "TOOL, WRITER, FIXTURES and WORK_DIR are required")
endif()
file(MAKE_DIRECTORY "${WORK_DIR}")
set(limits --max-input-bytes 67108864 --max-output-bytes 67108864
    --max-expansion-ratio 2048 --max-window-log 23)

function(run expected)
    execute_process(COMMAND "${TOOL}" ${ARGN}
        RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE errors)
    if(NOT "${result}" STREQUAL "${expected}")
        message(FATAL_ERROR "Expected ${expected}, got ${result}: ${ARGN}\n${output}\n${errors}")
    endif()
    set(output "${output}" PARENT_SCOPE)
    set(errors "${errors}" PARENT_SCOPE)
endfunction()

function(contains text expected)
    string(FIND "${text}" "${expected}" position)
    if(position LESS 0)
        message(FATAL_ERROR "Missing '${expected}' in:\n${text}")
    endif()
endfunction()

run(0 --help)
contains("${output}" "Usage: blend_inspect")
set(empty "${FIXTURES}/fixtures/empty.blend")
set(legacy "${FIXTURES}/corpus/blender-4.5.13/Untitled.blend")
set(modern "${FIXTURES}/corpus/blender-5.2.2/Untitled.blend")
run(0 "${empty}")
contains("${output}" "Blender version: 5.2 (502)")
contains("${output}" "Blocks: 266")
contains("${output}" "Datablocks: 1")
contains("${output}" "Objects: 0, Meshes: 0, Scenes: 1")
if(NOT errors STREQUAL "")
    message(FATAL_ERROR "Unexpected fixture diagnostics: ${errors}")
endif()
set(summary "${output}")
run(0 "${empty}" ${limits})
if(NOT output STREQUAL summary)
    message(FATAL_ERROR "Explicit limits changed the raw-file summary")
endif()
run(0 "${empty}" --blocks --dna --objects)
contains("${output}" "Block list (payload offsets in decoded bytes):")
contains("${output}" "\"DNA1\" offset=53954 length=134572")
contains("${output}" "\"ENDB\" offset=188558 length=0")
contains("${output}" "SDNA structures:")
contains("${output}" "\"Scene\" size=")
contains("${output}" "Raw Object datablocks:")
foreach(fixture IN ITEMS "${legacy}" "${modern}")
    run(0 "${fixture}" ${limits} --blocks --dna --objects)
    if(fixture STREQUAL legacy)
        contains("${output}" "Blender version: 4.5 (405)")
        contains("${output}" "Blocks: 1240")
        contains("${output}" "Datablocks: 36")
    else()
        contains("${output}" "Blender version: 5.2 (502)")
        contains("${output}" "Blocks: 1384")
        contains("${output}" "Datablocks: 37")
    endif()
    contains("${output}" "Objects: 3, Meshes: 1, Scenes: 1")
    contains("${output}" "SDNA structures:")
    contains("${output}" "\"ENDB\"")
    contains("${output}" "name=\"OBCube\"")
    contains("${output}" "name=\"OBCamera\"")
    contains("${output}" "name=\"OBLight\"")
    string(REGEX REPLACE
        "BLEND_BLOCK_UNKNOWN_CODE \\[unsupported\\]: [^\n]* \\(decoded byte [0-9]+\\) \\(block [0-9]+\\)\n"
        "" unexpected "${errors}")
    if(NOT unexpected STREQUAL "")
        message(FATAL_ERROR "Unexpected corpus diagnostics: ${errors}")
    endif()
endforeach()

run(2)
contains("${errors}" "BLEND_INSPECT_USAGE")
run(2 "${empty}" --unknown)
run(2 "${empty}" "${empty}")
run(2 "${empty}" --max-input-bytes 1)
foreach(value IN ITEMS 0 -1 +1 1junk 18446744073709551616)
    run(2 "${empty}" --max-input-bytes "${value}" --max-output-bytes 1
        --max-expansion-ratio 1 --max-window-log 23)
endforeach()
run(2 "${empty}" --max-input-bytes)
run(2 "${empty}" ${limits} --max-input-bytes 1)
run(2 "${empty}" --max-input-bytes 1 --max-output-bytes 1
    --max-expansion-ratio 1 --max-window-log 31)
run(1 "${WORK_DIR}/missing.blend")
contains("${errors}" "BLEND_IO_OPEN")
run(1 "${modern}")
contains("${errors}" "BLEND_COMPRESSION_LIMITS")
run(1 "${modern}" --max-input-bytes 67108864 --max-output-bytes 1
    --max-expansion-ratio 2048 --max-window-log 23)
contains("${errors}" "BLEND_COMPRESSION_OUTPUT_LIMIT")
run(1 "${legacy}" --max-input-bytes 1 --max-output-bytes 67108864
    --max-expansion-ratio 2048 --max-window-log 23)
contains("${errors}" "BLEND_COMPRESSION_INPUT_LIMIT")
run(1 "${FIXTURES}/fixtures/header_only.blend")
contains("${errors}" "BLEND_BLOCK_")
file(WRITE "${WORK_DIR}/invalid.blend" "not a blend file")
run(1 "${WORK_DIR}/invalid.blend")
contains("${errors}" "BLEND_HEADER_MAGIC")
file(WRITE "${WORK_DIR}/empty.blend" "")
run(1 "${WORK_DIR}/empty.blend")
contains("${errors}" "BLEND_HEADER_")
execute_process(COMMAND "${WRITER}" "${empty}" "${WORK_DIR}" RESULT_VARIABLE result)
if(NOT "${result}" STREQUAL "0")
    message(FATAL_ERROR "Binary fixture generation failed: ${result}")
endif()
run(1 "${WORK_DIR}/missing-dna.blend")
contains("${errors}" "BLEND_DNA_BLOCK")
run(1 "${WORK_DIR}/duplicate-dna.blend")
contains("${errors}" "BLEND_DNA_BLOCK")
run(1 "${WORK_DIR}/invalid-dna.blend")
contains("${errors}" "BLEND_DNA_SECTION")
contains("${errors}" "decoded byte 53954")
string(ASCII 230 164 156 230 159 187 unicode_dir)
file(MAKE_DIRECTORY "${WORK_DIR}/path with spaces/${unicode_dir}")
file(COPY_FILE "${empty}" "${WORK_DIR}/path with spaces/${unicode_dir}/empty.blend")
run(0 -- "${WORK_DIR}/path with spaces/${unicode_dir}/empty.blend")
if(NOT output STREQUAL summary)
    message(FATAL_ERROR "UTF-8 path changed the summary")
endif()